server:
  port: 8083

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/nexthood
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
