spring:
  datasource:
    url: jdbc:mysql://db:3306/notificationservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: #urmail
    password: #urpasswors
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true