server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8083
          predicates:
          - Path=/auth/**

        - id: user-service
          uri: http://localhost:8086
          predicates:
          - Path=/user/**

