server:
  port: 8086

spring:
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

management:
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  secret: ThisIsAReallyLongAndSecureSecretKey1234567890!